version: '3.7'

services:
  app:
    build: .
    container_name: catalogo-video-app
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - ./catalogo-video-app:/home/node/app
    ports: 
      - 3002:3000
    tty: true
